<a href="https://colab.research.google.com/github/francoriboratig/TP2-Datos/blob/master/Features%20B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
import pip
!pip install pycountry
import pycountry
!pip install https://github.com/elyase/geotext/archive/master.zip
from geotext import GeoText
from google.colab import files

%pylab inline

url='https://raw.githubusercontent.com/JulioCastillo1/TP1-Datos/master/train.csv'
url_test = 'https://raw.githubusercontent.com/francoriboratig/TP2-Datos/master/test.csv'

tweets = pd.read_csv(url)
test = pd.read_csv(url_test)
tweets.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Requirement already satisfied: pycountry in /usr/local/lib/python3.6/dist-packages (20.7.3)
Collecting https://github.com/elyase/geotext/archive/master.zip
  Using cached https://github.com/elyase/geotext/archive/master.zip
Requirement already satisfied (use --upgrade to upgrade): geotext==0.3.0 from https://github.com/elyase/geotext/archive/master.zip in /usr/local/lib/python3.6/dist-packages
Building wheels for collected packages: geotext
  Building wheel for geotext (setup.py) ... done
  Created wheel for geotext: filename=geotext-0.3.0-py2.py3-none-any.whl size=2272453 sha256=e58d39a830c006078eb7c6ec89c1e3fdd3f748988dc5a54745827aea90d5cac9
  Stored in directory: /tmp/pip-ephem-wheel-cache-i7eey0r0/wheels/f5/e3/84/31638877059a434d8601a764fc7565f2a9f7b6fb327085191e
Successfully built geotext
Populating the interactive namespace from numpy and matplotlib

/usr/local/lib/python3.6/dist-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['test']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"

   id keyword  ...                                               text target
0   1     NaN  ...  Our Deeds are the Reason of this #earthquake M...      1
1   4     NaN  ...             Forest fire near La Ronge Sask. Canada      1
2   5     NaN  ...  All residents asked to 'shelter in place' are ...      1
3   6     NaN  ...  13,000 people receive #wildfires evacuation or...      1
4   7     NaN  ...  Just got sent this photo from Ruby #Alaska as ...      1

[5 rows x 5 columns]

In [9]:
ps = PorterStemmer()
stopwordsList = stopwords.words('english')

def nlp(texts):
   results=[] 
   for i in range(0, len(texts)):
      processed = re.sub('[^a-aA-z]',' ',texts[i])
      processed = processed.lower()
      processed = processed.split()
      processed = [ps.stem(word) for word in processed if not word in stopwordsList]
      processed = ' '.join(processed)
      results.append(processed)
   return results
   
tweets['text'] = nlp(tweets['text'])
tweets.head(10)

   id keyword  ...                                               text target
0   1     NaN  ...          deed reason earthquak may allah forgiv us      1
1   4     NaN  ...               forest fire near la rong sask canada      1
2   5     NaN  ...  resid ask shelter place notifi offic evacu she...      1
3   6     NaN  ...        peopl receiv wildfir evacu order california      1
4   7     NaN  ...  got sent photo rubi alaska smoke wildfir pour ...      1
5   8     NaN  ...  rockyfir updat california hwi close direct due...      1
6  10     NaN  ...  flood disast heavi rain caus flash flood stree...      1
7  13     NaN  ...                             top hill see fire wood      1
8  14     NaN  ...             emerg evacu happen build across street      1
9  15     NaN  ...                           afraid tornado come area      1

[10 rows x 5 columns]

In [10]:
tweets.to_csv('train-featuresB.csv')
test.to_csv('test-featuresB.csv')
#files.download('train-featuresB.csv')
#files.download('test-featuresB.csv')